### ISSUE TITLE
聚合根没有跟ORM解耦

### ISSUE THREAD

**Issue by ddnine** [daheige/go-ddd-api#1]
我看在聚合根里直接使用了GROM,这使得聚合根耦合了基础层.
我的想法是在基础层使用配置类来进行聚合根的数据库定义.

**Comment by daheige** [comment]
对于这个点，其实不用那么严格的，数据库的实体类型和业务建模中的领域层的实体对象是可以分开的，看每个团队的选择。做的好的确实是需要db里面的模型对象和业务模型定义是隔离开来的，也就是防腐处理，避免业务建模的实体对象和数据库表模型混合在一起的。因为从《架构整洁之道》中提到的数据库其实也是一种实现细节，在开发过程中，要面向接口设计的开发，而不用关注底层实现细节，也就是底层策略指向高层策略的模式。

**Comment by daheige** [comment]
你提到的这个点，在《实现领域驱动设计》中有提到的，在一定程度是可以的，不过也不必严格扣概念，把DDD的东西全部搬过来的哈。另外这个项目，是一个DDD Lite模式，也就是从实际项目的角度出发，是可以的，因为团队组织架构规模不一样，如果项目确实大了，从长期的维护成本来看，确实需要做隔离，防腐处理，也就是领域domain中的entity定义和数据表模型的实体对象要分开，在底层实现的时候做好对应的转换，类似DTO模式。
